"""
Mining-event detection from raw monerod log content.

Factored out of agents/simulation_monitor.py: the regex patterns and the
line-walking logic for "what blocks were locally mined in this chunk of
log" are completely free of agent state. The agent still owns the per-file
position tracking and the de-duplication / accounting (those touch many
self.* attributes), but the lexical pattern matching lives here.
"""

import re
from typing import List


# Pattern 1: "mined new block" with height
_MINED_PATTERN = re.compile(
    r'mined new block.*height[=:\s]*(\d+)',
    re.IGNORECASE
)

# Pattern 2: "BLOCK SUCCESSFULLY ADDED" followed by block details
_BLOCK_ADDED_PATTERN = re.compile(
    r'\+{5,}\s*BLOCK SUCCESSFULLY ADDED',
    re.IGNORECASE
)

# Pattern 3: Block ID/hash after successful add (kept for parity with the
# original, even though it isn't currently consulted by the parser)
_BLOCK_ID_PATTERN = re.compile(
    r'id:\s*<([0-9a-f]{64})>',
    re.IGNORECASE
)

# Pattern 4: Height from block info
_HEIGHT_PATTERN = re.compile(
    r'HEIGHT\s+(\d+)',
    re.IGNORECASE
)

# Pattern 5: PoW indicator (present in all blocks, not just mined ones)
_POW_PATTERN = re.compile(
    r'PoW:\s*<([0-9a-f]{64})>',
    re.IGNORECASE
)

# Pattern 6: Received block from network (means NOT locally mined)
_RECEIVED_BLOCK_PATTERN = re.compile(
    r'Received NOTIFY_NEW_FLUFFY_BLOCK|NOTIFY_NEW_BLOCK',
    re.IGNORECASE
)

# Pattern 7: generateblocks RPC call (means locally mined via RPC)
_GENERATEBLOCKS_PATTERN = re.compile(
    r'generateblocks',
    re.IGNORECASE
)


def parse_mining_events(content: str) -> List[int]:
    """
    Scan a chunk of monerod log content and return the heights of all
    locally-mined blocks observed in it.

    Two detection paths, matching the original agent logic:
      1. A single line matching "mined new block ... height=N" yields N.
      2. A "BLOCK SUCCESSFULLY ADDED" marker preceded (within the prior
         5 lines) by a "generateblocks" RPC call and not preceded by an
         inbound NOTIFY_NEW_(FLUFFY_)BLOCK -- with a "HEIGHT N" line
         within the next 10 lines -- yields N (for N > 0; genesis is
         excluded).

    The function does NOT deduplicate against previous calls or across
    agents -- the caller (SimulationMonitorAgent._record_block_mined)
    handles that.

    Args:
        content: Raw log text to scan.

    Returns:
        List of locally-mined block heights, in the order encountered.
    """
    heights: List[int] = []

    lines = content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i]

        # Check for "mined new block" pattern
        mined_match = _MINED_PATTERN.search(line)
        if mined_match:
            heights.append(int(mined_match.group(1)))
            i += 1
            continue

        # Check for "BLOCK SUCCESSFULLY ADDED" pattern
        if _BLOCK_ADDED_PATTERN.search(line):
            # Look BACK to check if this was locally mined vs received from network
            # Received blocks have "NOTIFY_NEW_FLUFFY_BLOCK" before them
            # Mined blocks have "generateblocks" RPC call before them
            is_received_from_network = False
            is_locally_mined = False

            # Look back up to 5 lines for context
            for j in range(max(0, i - 5), i):
                check_line = lines[j]
                if _RECEIVED_BLOCK_PATTERN.search(check_line):
                    is_received_from_network = True
                    break
                if _GENERATEBLOCKS_PATTERN.search(check_line):
                    is_locally_mined = True

            # Skip if this block was received from network (not locally mined)
            if is_received_from_network:
                i += 1
                continue

            # Look ahead for height info
            block_height = None
            for j in range(i, min(i + 10, len(lines))):
                check_line = lines[j]
                height_match = _HEIGHT_PATTERN.search(check_line)
                if height_match:
                    block_height = int(height_match.group(1))
                    break

            # Record if we have height, it was locally mined, and it's not genesis block
            # Genesis block (height 0) is generated by all nodes, not "mined"
            if block_height is not None and block_height > 0 and is_locally_mined:
                heights.append(block_height)

        i += 1

    return heights
