# Test configuration for Hybrid peer mode
# Combines topology-based connections with peer discovery
# Uses GML network with Ring topology + dynamic discovery

general:
  stop_time: "3m"
  fresh_blockchain: true
  log_level: info

network:
  path: "testnet.gml"
  peer_mode: "Hybrid"
  topology: "Ring"
  seed_nodes:
    - "10.0.0.10:28080"
    - "192.168.0.10:28080"

agents:
  user_agents:
    # Agents distributed across GML network nodes
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "40"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "30"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "10"

    # Regular users with hybrid connectivity
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "45"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "60"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "90"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"