# MoneroSim Configuration File
# This file defines the parameters for Monero network simulation

python_venv: /home/lever65/monerosim_dev/monerosim/venv
general:
  # Simulation stop time (supports human-readable formats like "1h", "30m", "3600s")
  stop_time: "10800s"  # 3 hours for full run
  # Start with fresh blockchain (clears existing data)
  fresh_blockchain: true

agents:
  regular_users:
    count: 2
    transaction_interval: 300  # 5 minutes between transactions
    min_transaction_amount: 0.1
    max_transaction_amount: 1.0
  marketplaces:
    count: 1
  mining_pools:
    count: 1
    mining_threads: 1
    pool_fee: 0.01
block_generation:
  interval: 120  # 2 minutes between blocks
  pools_per_round: 1
  difficulty_adjustment: "fixed"
