# MoneroSim Configuration File
# This file defines the parameters for Monero network simulation

general:
  # Simulation stop time (supports human-readable formats like "1h", "30m", "3600s")
  stop_time: "20s"
  # Start with fresh blockchain (clears existing data)
  fresh_blockchain: true

nodes:
  - name: "A0"
    ip: "11.0.0.1"
    port: 28080
    start_time: "0s"
    mining: true
    fixed_difficulty: 1
  
  - name: "A1"
    ip: "11.0.0.2"
    port: 28080
    start_time: "1s"
    fixed_difficulty: 1
