# MoneroSim Configuration File
# This file defines the parameters for Monero network simulation

general:
  # Simulation stop time (supports human-readable formats like "1h", "30m", "3600s")
  stop_time: "5m"

monero:
  # List of node types/groups to simulate
  nodes:
    - count: 5
      name: "A"
      base_commit: "shadow-complete"
