# Medium configuration for end-to-end testing
# 5 miners and 10 regular users
# Simulation duration: 1 hour

general:
  stop_time: "1h"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"

agents:
  user_agents:
    # Miner 1 - 25% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "25"
        can_receive_distributions: true

    # Miner 2 - 25% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "25"
        can_receive_distributions: "1"

    # Miner 3 - 20% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "20"
        can_receive_distributions: false

    # Miner 4 - 20% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "20"
        can_receive_distributions: "0"

    # Miner 5 - 10% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "10"
        can_receive_distributions: "yes"

    # Regular Users with varying transaction patterns and distribution settings
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: false

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "120"
        min_transaction_amount: "1.0"
        max_transaction_amount: "5.0"
        can_receive_distributions: "true"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "45"
        min_transaction_amount: "0.2"
        max_transaction_amount: "3.0"
        can_receive_distributions: "false"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "180"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.5"
        can_receive_distributions: "on"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "75"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.5"
        can_receive_distributions: "off"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "150"
        min_transaction_amount: "2.0"
        max_transaction_amount: "10.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "100"
        min_transaction_amount: "0.1"
        max_transaction_amount: "0.8"
        can_receive_distributions: false

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "65"
        min_transaction_amount: "0.4"
        max_transaction_amount: "2.5"
        can_receive_distributions: "true"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "110"
        min_transaction_amount: "0.7"
        max_transaction_amount: "4.0"
        can_receive_distributions: "false"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"