# Comprehensive Internet Topology Test Configuration
# Tests GML parsing, hierarchical IP assignment, multi-layered network structure,
# and inter-network communication validation across multiple Autonomous Systems

general:
  stop_time: "30m"  # Shorter duration for testing
  fresh_blockchain: true
  log_level: debug

network:
  path: "comprehensive_internet_topology_test.gml"

agents:
  user_agents:
    # AS 65001 Agents (Large ISP Network - 10.0.0.0/24)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "30"
        can_receive_distributions: true
        location: "New_York"
        network_role: "miner_isp_a"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true
        location: "New_York"
        network_role: "user_isp_a_nyc"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "1.0"
        max_transaction_amount: "5.0"
        can_receive_distributions: false
        location: "Los_Angeles"
        network_role: "user_isp_a_lax"

    # AS 65002 Agents (Regional ISP Network - 192.168.0.0/24)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "25"
        can_receive_distributions: true
        location: "Chicago"
        network_role: "miner_isp_b"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "45"
        min_transaction_amount: "0.2"
        max_transaction_amount: "1.5"
        can_receive_distributions: true
        location: "Chicago"
        network_role: "user_isp_b_chi"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "120"
        min_transaction_amount: "0.1"
        max_transaction_amount: "0.8"
        can_receive_distributions: false
        location: "Seattle"
        network_role: "user_isp_b_sea"

    # AS 65003 Agents (Data Center Network - 172.16.0.0/24)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "20"
        can_receive_distributions: true
        location: "Ashburn"
        network_role: "miner_datacenter"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "30"
        min_transaction_amount: "2.0"
        max_transaction_amount: "10.0"
        can_receive_distributions: true
        location: "Ashburn"
        network_role: "user_datacenter"

    # AS 65004 Agents (International Network - 203.0.113.0/24)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "180"
        min_transaction_amount: "0.5"
        max_transaction_amount: "3.0"
        can_receive_distributions: true
        location: "London"
        network_role: "user_international_eu"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "300"
        min_transaction_amount: "0.3"
        max_transaction_amount: "2.0"
        can_receive_distributions: false
        location: "Singapore"
        network_role: "user_international_asia"

    # AS 65005 Agents (University Network - 198.51.100.0/24)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "15"
        can_receive_distributions: true
        location: "Cambridge"
        network_role: "miner_university"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "75"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: true
        location: "Cambridge"
        network_role: "user_university_research"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "150"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.5"
        can_receive_distributions: false
        location: "Cambridge"
        network_role: "user_university_general"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"
    - script: "scripts.test_p2p_connectivity"