general:
  stop_time: "1h"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"
  peer_mode: "Dynamic"
  topology: "Mesh"

agents:
  user_agents:
    # Miner 1
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "50"
        can_receive_distributions: true

    # Miner 2
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "50"
        can_receive_distributions: true

    # Regular user 1
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    # Regular user 2
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"