# Large configuration for end-to-end testing
# 10 miners and 20 regular users
# Simulation duration: 2 hours

general:
  stop_time: "2h"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"

agents:
  user_agents:
    # Miner 1 - 15% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "15"
        can_receive_distributions: true

    # Miner 2 - 15% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "15"
        can_receive_distributions: true

    # Miner 3 - 12% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "12"
        can_receive_distributions: false

    # Miner 4 - 12% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "12"
        can_receive_distributions: false

    # Miner 5 - 10% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "10"
        can_receive_distributions: true

    # Miner 6 - 10% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "10"
        can_receive_distributions: true

    # Miner 7 - 8% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "8"
        can_receive_distributions: false

    # Miner 8 - 8% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "8"
        can_receive_distributions: false

    # Miner 9 - 5% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "5"
        can_receive_distributions: true

    # Miner 10 - 5% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "5"
        can_receive_distributions: false

    # Regular Users with diverse transaction patterns and distribution settings
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: false

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "120"
        min_transaction_amount: "1.0"
        max_transaction_amount: "5.0"
        can_receive_distributions: "true"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "45"
        min_transaction_amount: "0.2"
        max_transaction_amount: "3.0"
        can_receive_distributions: "false"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "180"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.5"
        can_receive_distributions: "on"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "75"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.5"
        can_receive_distributions: "off"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "150"
        min_transaction_amount: "2.0"
        max_transaction_amount: "10.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "100"
        min_transaction_amount: "0.1"
        max_transaction_amount: "0.8"
        can_receive_distributions: false

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "65"
        min_transaction_amount: "0.4"
        max_transaction_amount: "2.5"
        can_receive_distributions: "true"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "110"
        min_transaction_amount: "0.7"
        max_transaction_amount: "4.0"
        can_receive_distributions: "false"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "130"
        min_transaction_amount: "0.15"
        max_transaction_amount: "1.2"
        can_receive_distributions: "1"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "85"
        min_transaction_amount: "0.25"
        max_transaction_amount: "3.5"
        can_receive_distributions: "0"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "170"
        min_transaction_amount: "0.08"
        max_transaction_amount: "0.7"
        can_receive_distributions: "yes"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "95"
        min_transaction_amount: "0.35"
        max_transaction_amount: "2.8"
        can_receive_distributions: "no"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "140"
        min_transaction_amount: "1.5"
        max_transaction_amount: "7.0"
        can_receive_distributions: "on"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "80"
        min_transaction_amount: "0.12"
        max_transaction_amount: "0.9"
        can_receive_distributions: "off"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "160"
        min_transaction_amount: "0.6"
        max_transaction_amount: "3.2"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "105"
        min_transaction_amount: "0.45"
        max_transaction_amount: "1.8"
        can_receive_distributions: false

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "125"
        min_transaction_amount: "0.9"
        max_transaction_amount: "6.0"
        can_receive_distributions: "true"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"