general:
  stop_time: "30m"
  log_level: info

network:
  type: "1_gbit_switch"
  peer_mode: "Hardcoded"
  topology: "Star"  # Options: Star, Mesh, Ring, Dag
  seed_nodes: []

agents:
  user_agents:
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: "true"
        hashrate: "50"
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"

  block_controller:
    script: "agents.block_controller"