# 55-agent configuration for GML topology simulation
# 5 miners with specified hashrates and 50 regular users
# Simulation duration: 6 hours

general:
  stop_time: "6h"
  fresh_blockchain: true
  log_level: info

network:
  path: "caida_connected_sparse_with_loops_fixed.gml"
  peer_mode: "Hybrid"
  topology: "Ring"
  seed_nodes:
    - "192.168.1.10:28080"
    - "192.168.1.11:28080"

agents:
  user_agents:
    # Miners with specified hashrates
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "20"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "15"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "15"
        can_receive_distributions: true

    # Regular users (50 total)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "120"
        min_transaction_amount: "1.0"
        max_transaction_amount: "5.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "45"
        min_transaction_amount: "0.2"
        max_transaction_amount: "3.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "180"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "75"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "150"
        min_transaction_amount: "2.0"
        max_transaction_amount: "10.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "100"
        min_transaction_amount: "0.1"
        max_transaction_amount: "0.8"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "65"
        min_transaction_amount: "0.4"
        max_transaction_amount: "2.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "110"
        min_transaction_amount: "0.7"
        max_transaction_amount: "4.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "130"
        min_transaction_amount: "0.15"
        max_transaction_amount: "1.2"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "85"
        min_transaction_amount: "0.25"
        max_transaction_amount: "3.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "170"
        min_transaction_amount: "0.08"
        max_transaction_amount: "0.7"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "95"
        min_transaction_amount: "0.35"
        max_transaction_amount: "2.8"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "140"
        min_transaction_amount: "1.5"
        max_transaction_amount: "7.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "80"
        min_transaction_amount: "0.12"
        max_transaction_amount: "0.9"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "160"
        min_transaction_amount: "0.6"
        max_transaction_amount: "3.2"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "105"
        min_transaction_amount: "0.45"
        max_transaction_amount: "1.8"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "125"
        min_transaction_amount: "0.9"
        max_transaction_amount: "6.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "70"
        min_transaction_amount: "0.3"
        max_transaction_amount: "2.2"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "135"
        min_transaction_amount: "0.2"
        max_transaction_amount: "1.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "115"
        min_transaction_amount: "0.8"
        max_transaction_amount: "4.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "155"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "50"
        min_transaction_amount: "0.4"
        max_transaction_amount: "2.8"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "145"
        min_transaction_amount: "1.2"
        max_transaction_amount: "8.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "165"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "55"
        min_transaction_amount: "0.6"
        max_transaction_amount: "3.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "175"
        min_transaction_amount: "0.02"
        max_transaction_amount: "0.4"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "40"
        min_transaction_amount: "0.5"
        max_transaction_amount: "3.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "190"
        min_transaction_amount: "0.3"
        max_transaction_amount: "2.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "62"
        min_transaction_amount: "0.55"
        max_transaction_amount: "2.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "92"
        min_transaction_amount: "0.12"
        max_transaction_amount: "1.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "122"
        min_transaction_amount: "1.1"
        max_transaction_amount: "5.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "47"
        min_transaction_amount: "0.22"
        max_transaction_amount: "3.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "182"
        min_transaction_amount: "0.06"
        max_transaction_amount: "0.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "77"
        min_transaction_amount: "0.32"
        max_transaction_amount: "1.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "152"
        min_transaction_amount: "2.1"
        max_transaction_amount: "10.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "102"
        min_transaction_amount: "0.11"
        max_transaction_amount: "0.9"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "67"
        min_transaction_amount: "0.42"
        max_transaction_amount: "2.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "112"
        min_transaction_amount: "0.72"
        max_transaction_amount: "4.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "132"
        min_transaction_amount: "0.17"
        max_transaction_amount: "1.3"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "87"
        min_transaction_amount: "0.27"
        max_transaction_amount: "3.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "172"
        min_transaction_amount: "0.09"
        max_transaction_amount: "0.8"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "97"
        min_transaction_amount: "0.37"
        max_transaction_amount: "2.9"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "142"
        min_transaction_amount: "1.6"
        max_transaction_amount: "7.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "82"
        min_transaction_amount: "0.14"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "162"
        min_transaction_amount: "0.62"
        max_transaction_amount: "3.3"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "107"
        min_transaction_amount: "0.47"
        max_transaction_amount: "1.9"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "127"
        min_transaction_amount: "0.92"
        max_transaction_amount: "6.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "72"
        min_transaction_amount: "0.32"
        max_transaction_amount: "2.3"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "137"
        min_transaction_amount: "0.22"
        max_transaction_amount: "1.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "117"
        min_transaction_amount: "0.82"
        max_transaction_amount: "4.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "157"
        min_transaction_amount: "0.07"
        max_transaction_amount: "0.7"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "52"
        min_transaction_amount: "0.42"
        max_transaction_amount: "2.9"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "147"
        min_transaction_amount: "1.3"
        max_transaction_amount: "8.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "167"
        min_transaction_amount: "0.11"
        max_transaction_amount: "1.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "57"
        min_transaction_amount: "0.62"
        max_transaction_amount: "3.6"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "177"
        min_transaction_amount: "0.03"
        max_transaction_amount: "0.5"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "42"
        min_transaction_amount: "0.52"
        max_transaction_amount: "3.1"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "192"
        min_transaction_amount: "0.32"
        max_transaction_amount: "2.1"
        can_receive_distributions: true

  block_controller:
    script: "agents.block_controller"