# Global Network Configuration - 20 Agents Across 5 Continents
# 5 miners with distributed hashrate and 15 mining distribution receivers
# Uses GML-based network topology for realistic global network simulation

general:
  stop_time: "5h"
  fresh_blockchain: true
  log_level: info

network:
  path: "global_network_20_nodes_no_comments.gml"

agents:
  user_agents:
    # North America Miners
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "25"
        can_receive_distributions: true
        location: "North America"
        city: "New York"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"
        can_receive_distributions: true
        location: "North America"
        city: "Chicago"

    # Europe Miners
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"
        can_receive_distributions: true
        location: "Europe"
        city: "London"

    # Asia Miners
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"
        can_receive_distributions: true
        location: "Asia"
        city: "Tokyo"

    # Africa Miner
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "15"
        can_receive_distributions: true
        location: "Africa"
        city: "Johannesburg"

    # North America Distribution Receivers
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true
        location: "North America"
        city: "Los Angeles"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.5"
        can_receive_distributions: true
        location: "North America"
        city: "Toronto"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "75"
        min_transaction_amount: "0.4"
        max_transaction_amount: "1.8"
        can_receive_distributions: true
        location: "North America"
        city: "Miami"

    # Europe Distribution Receivers
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "85"
        min_transaction_amount: "0.2"
        max_transaction_amount: "1.2"
        can_receive_distributions: true
        location: "Europe"
        city: "Frankfurt"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "70"
        min_transaction_amount: "0.6"
        max_transaction_amount: "2.5"
        can_receive_distributions: true
        location: "Europe"
        city: "Paris"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "95"
        min_transaction_amount: "0.1"
        max_transaction_amount: "0.8"
        can_receive_distributions: true
        location: "Europe"
        city: "Amsterdam"

    # Asia Distribution Receivers
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "110"
        min_transaction_amount: "0.8"
        max_transaction_amount: "3.0"
        can_receive_distributions: true
        location: "Asia"
        city: "Hong Kong"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "80"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.2"
        can_receive_distributions: true
        location: "Asia"
        city: "Singapore"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "120"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.5"
        can_receive_distributions: true
        location: "Asia"
        city: "Seoul"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "100"
        min_transaction_amount: "0.7"
        max_transaction_amount: "2.8"
        can_receive_distributions: true
        location: "Asia"
        city: "Mumbai"

    # South America Distribution Receivers
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "140"
        min_transaction_amount: "0.4"
        max_transaction_amount: "1.8"
        can_receive_distributions: true
        location: "South America"
        city: "Sao Paulo"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "130"
        min_transaction_amount: "0.2"
        max_transaction_amount: "1.0"
        can_receive_distributions: true
        location: "South America"
        city: "Buenos Aires"

    # Africa Distribution Receivers
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "160"
        min_transaction_amount: "0.3"
        max_transaction_amount: "1.3"
        can_receive_distributions: true
        location: "Africa"
        city: "Cairo"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "150"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: true
        location: "Africa"
        city: "Lagos"

  block_controller:
    script: "agents.block_controller"

  miner_distributor:
    script: "agents.miner_distributor"
    attributes:
      distribution_interval: "300"
      min_distribution_amount: "0.1"
      max_distribution_amount: "1.0"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"