general:
  stop_time: "6h"
  fresh_blockchain: true
  log_level: debug

network:
  type: "1_gbit_switch"
  peer_mode: "Dynamic"
  topology: "Mesh"

agents:
  user_agents:
    # Miner 1 - 25% hashrate
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: true
        hashrate: "25"

    # Miner 2 - 25% hashrate
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: true
        hashrate: "25"

    # Miner 3 - 20% hashrate
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: true
        hashrate: "20"

    # Miner 4 - 15% hashrate
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: true
        hashrate: "15"

    # Miner 5 - 15% hashrate
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        is_miner: true
        hashrate: "15"

    # Standard Node 1 - North America (NYC)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "60"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"

    # Standard Node 2 - North America (Chicago)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "90"
        min_transaction_amount: "0.05"
        max_transaction_amount: "0.5"

    # Standard Node 3 - North America (LA)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "45"
        min_transaction_amount: "0.2"
        max_transaction_amount: "2.0"

    # Standard Node 4 - North America (Toronto)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "120"
        min_transaction_amount: "0.5"
        max_transaction_amount: "3.0"

    # Standard Node 5 - North America (Vancouver)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "75"
        min_transaction_amount: "0.15"
        max_transaction_amount: "1.5"

    # Standard Node 6 - North America (Seattle)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "100"
        min_transaction_amount: "0.08"
        max_transaction_amount: "0.8"

    # Standard Node 7 - North America (Miami)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "85"
        min_transaction_amount: "0.12"
        max_transaction_amount: "1.2"

    # Standard Node 8 - Europe (London)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "50"
        min_transaction_amount: "0.25"
        max_transaction_amount: "2.5"

    # Standard Node 9 - Europe (Frankfurt)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "65"
        min_transaction_amount: "0.18"
        max_transaction_amount: "1.8"

    # Standard Node 10 - Europe (Paris)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "70"
        min_transaction_amount: "0.3"
        max_transaction_amount: "3.0"

    # Standard Node 11 - Europe (Amsterdam)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "55"
        min_transaction_amount: "0.4"
        max_transaction_amount: "4.0"

    # Standard Node 12 - Europe (Zurich)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "80"
        min_transaction_amount: "0.22"
        max_transaction_amount: "2.2"

    # Standard Node 13 - Europe (Stockholm)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "95"
        min_transaction_amount: "0.14"
        max_transaction_amount: "1.4"

    # Standard Node 14 - Asia (Tokyo)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "40"
        min_transaction_amount: "0.35"
        max_transaction_amount: "3.5"

    # Standard Node 15 - Asia (Seoul)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "110"
        min_transaction_amount: "0.06"
        max_transaction_amount: "0.6"

    # Standard Node 16 - Asia (Hong Kong)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "125"
        min_transaction_amount: "0.45"
        max_transaction_amount: "4.5"

    # Standard Node 17 - Asia (Singapore)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "35"
        min_transaction_amount: "0.28"
        max_transaction_amount: "2.8"

    # Standard Node 18 - Asia (Mumbai)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "105"
        min_transaction_amount: "0.16"
        max_transaction_amount: "1.6"

    # Standard Node 19 - Asia (Bangalore)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: true
        transaction_interval: "130"
        min_transaction_amount: "0.09"
        max_transaction_amount: "0.9"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"

