# Large-scale agent-based simulation configuration
# 100 regular users, 10 marketplaces, 5 mining pools

general:
  simulation_duration: 3600  # 60 minutes
  log_level: warning  # Less verbose for large simulations
  
network:
  # Simple network topology
  type: simple
  
agents:
  # Regular users who send transactions
  regular_users:
    count: 100
    transaction_interval: 120  # seconds between transactions
    min_transaction_amount: 0.01
    max_transaction_amount: 10.0
    
  # Marketplaces that receive payments
  marketplaces:
    count: 10
    
  # Mining pools that generate blocks
  mining_pools:
    count: 5
    
# Block generation settings
block_generation:
  interval: 120  # seconds between blocks
  pools_per_round: 2  # how many pools mine simultaneously