# Large-scale agent-based simulation configuration
# 100 regular users, 10 marketplaces, 5 mining pools

general:
  stop_time: "60m"
  fresh_blockchain: true
  log_level: warning  # Less verbose for large simulations
  
network:
  type: simple
  bandwidth: "10Gbps"
  latency: "5ms"
  
agents:
  # Regular users who send transactions
  regular_users:
    count: 100
    transaction_interval: 120  # seconds between transactions
    min_transaction_amount: 0.01
    max_transaction_amount: 10.0
    wallet_settings:
      initial_balance: 100.0
    
  # Marketplaces that receive payments
  marketplaces:
    count: 10
    payment_processing_delay: 10
    
  # Mining pools that generate blocks
  mining_pools:
    count: 5
    mining_threads: 2
    pool_fee: 0.02
    
# Block generation settings
block_generation:
  interval: 120  # seconds between blocks
  pools_per_round: 2  # how many pools mine simultaneously
  difficulty_adjustment: "fixed"