# 5-Agent Test Configuration for can_receive_distributions Validation
# Tests the fixed configuration with mixed distribution settings
# Simulation duration: 20 minutes

general:
  stop_time: "20m"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"

agents:
  user_agents:
    # Miner 1 - High hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "60"
        can_receive_distributions: true

    # Miner 2 - Low hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "40"
        can_receive_distributions: false

    # Regular User 1 - Can receive distributions (string format)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: "yes"

    # Regular User 2 - Cannot receive distributions (numeric format)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: "0"

    # Miner Distributor Agent - Distributes funds to eligible recipients
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.miner_distributor"
      attributes:
        transaction_frequency: "30"
        recipient_selection: "random"
        can_receive_distributions: false

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"