general:
  stop_time: 1h
  fresh_blockchain: true
  log_level: info
network:
  type: 1_gbit_switch
agents:
  user_agents:
  - daemon: monerod
    wallet: monero-wallet-rpc
    attributes:
      hashrate: '25'
      is_miner: 'true'
  - daemon: monerod
    wallet: monero-wallet-rpc
    attributes:
      hashrate: '25'
      is_miner: 'true'
  - daemon: monerod
    wallet: monero-wallet-rpc
    attributes:
      hashrate: '20'
      is_miner: 'true'
  - daemon: monerod
    wallet: monero-wallet-rpc
    attributes:
      hashrate: '20'
      is_miner: 'true'
  - daemon: monerod
    wallet: monero-wallet-rpc
    attributes:
      hashrate: '10'
      is_miner: 'true'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '60'
      min_transaction_amount: '0.5'
      max_transaction_amount: '2.0'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '90'
      min_transaction_amount: '0.1'
      max_transaction_amount: '1.0'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '120'
      min_transaction_amount: '1.0'
      max_transaction_amount: '5.0'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '45'
      min_transaction_amount: '0.2'
      max_transaction_amount: '3.0'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '180'
      min_transaction_amount: '0.05'
      max_transaction_amount: '0.5'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '75'
      min_transaction_amount: '0.3'
      max_transaction_amount: '1.5'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '150'
      min_transaction_amount: '2.0'
      max_transaction_amount: '10.0'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '100'
      min_transaction_amount: '0.1'
      max_transaction_amount: '0.8'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '65'
      min_transaction_amount: '0.4'
      max_transaction_amount: '2.5'
  - daemon: monerod
    wallet: monero-wallet-rpc
    user_script: agents.regular_user
    attributes:
      transaction_interval: '110'
      min_transaction_amount: '0.7'
      max_transaction_amount: '4.0'
  block_controller:
    script: agents.block_controller
  pure_script_agents:
  - script: scripts.monitor
  - script: scripts.sync_check
