# Test configuration for Ring topology
# Nodes connect in circular pattern: 0→1→2→0
# Requirements: ≥3 agents

general:
  stop_time: "3m"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"
  peer_mode: "Hardcoded"
  topology: "Ring"
  seed_nodes:
    - "192.168.0.10:28080"  # Will be updated to first agent IP

agents:
  user_agents:
    # Ring connections: 0→1→2→0
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "40"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "30"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "30"

    # Additional nodes in ring
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "60"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "90"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"