# Medium-scale agent-based simulation configuration
# 10 regular users, 3 marketplaces, 2 mining pools

general:
  stop_time: "4h"
  fresh_blockchain: true
  log_level: info
  
network:
  type: simple
  bandwidth: "1Gbps"
  latency: "10ms"
  
agents:
  # Regular users who send transactions
  regular_users:
    count: 10
    transaction_interval: 60  # seconds between transactions
    min_transaction_amount: 0.1
    max_transaction_amount: 5.0
    
  # Marketplaces that receive payments
  marketplaces:
    count: 2
    payment_processing_delay: 5
    
  # Mining pools that generate blocks
  mining_pools:
    count: 2
    mining_threads: 1
    
# Block generation settings
block_generation:
  interval: 60  # seconds between blocks
  pools_per_round: 1  # how many pools mine simultaneously
  difficulty_adjustment: "fixed"
