# MoneroSim Configuration File
# This file defines the parameters for Monero network simulation

general:
  # Simulation stop time (supports human-readable formats like "1h", "30m", "3600s")
  stop_time: "5m"

nodes:
  - name: "A0"
    ip: "11.0.0.1"
    port: 28080
    start_time: "10s"
    mining: true
    fixed_difficulty: 200
  
  - name: "A1"
    ip: "11.0.0.2"
    port: 28080
    start_time: "120s"  # Start after A0 has time to mine blocks
