# Small configuration for end-to-end testing
# 2 miners and 2 regular users
# Simulation duration: 30 minutes

general:
  stop_time: "30m"
  fresh_blockchain: true
  log_level: info

network:
  path: "testnet.gml"
  peer_mode: "Hybrid"
  topology: "Ring"
  seed_nodes:
    - "10.0.0.10:28080"
    - "192.168.0.10:28080"

agents:
  user_agents:
    # Miner 1 - 60% hashrate, can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "60"
        can_receive_distributions: true

    # Miner 2 - 40% hashrate, cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      is_miner: true
      attributes:
        hashrate: "40"
        can_receive_distributions: false

    # Regular User 1 - can receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.5"
        max_transaction_amount: "2.0"
        can_receive_distributions: "true"

    # Regular User 2 - cannot receive distributions
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "90"
        min_transaction_amount: "0.1"
        max_transaction_amount: "1.0"
        can_receive_distributions: "false"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"