# Test configuration for Mesh topology
# Every node connects to every other node
# Requirements: Any number (warning for >50)
# Best for small networks (≤10 agents)

general:
  stop_time: "3m"
  fresh_blockchain: true
  log_level: info

network:
  type: "1_gbit_switch"
  peer_mode: "Hardcoded"
  topology: "Mesh"
  seed_nodes:
    - "192.168.0.10:28080"  # Will be updated to first agent IP

agents:
  user_agents:
    # All agents connect to each other
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "30"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "30"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: "true"
        hashrate: "20"

    # Regular users in fully connected network
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "45"

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        can_receive_distributions: "true"
        transaction_interval: "60"

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"