general:
  stop_time: "6h"
  fresh_blockchain: true
  log_level: info

network:
  path: "global_network_20_nodes_clean_fixed.gml"
  peer_mode: "Dynamic"
  topology: "Mesh"

agents:
  user_agents:
    # Miner 1
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    # Miner 2
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    # Miner 3
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    # Miner 4
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      attributes:
        is_miner: true
        hashrate: "25"
        can_receive_distributions: true

    # Regular users (16 total to make 20 agents)
    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

    - daemon: "monerod"
      wallet: "monero-wallet-rpc"
      user_script: "agents.regular_user"
      attributes:
        transaction_interval: "60"
        min_transaction_amount: "0.01"
        max_transaction_amount: "1.0"
        can_receive_distributions: true

  block_controller:
    script: "agents.block_controller"

  pure_script_agents:
    - script: "scripts.monitor"
    - script: "scripts.sync_check"