#!/usr/bin/env bash
#
# scaling_sweep.sh — rapid-iteration tool for calibrating the Shadow
# event-storm constant (SHADOW_EVENT_COST_S) in scripts/calibrate.py.
#
# Runs a small simulation for each (N, M, interval) tuple in a grid,
# measures how fast Shadow advances simulated time relative to wall time,
# and appends results to a CSV. Each run is small (~minutes, not hours)
# so dozens of data points can be collected per day.
#
# Usage:
#   ./scripts/scaling_sweep.sh <N> <M> <interval>          # one run
#   ./scripts/scaling_sweep.sh --grid                       # run default grid
#   CSV=/tmp/results.csv ./scripts/scaling_sweep.sh --grid  # custom CSV path
#
# Fields recorded per run:
#   N         = number of user agents
#   M         = total simulated network nodes (miners + users + relays)
#   interval  = transaction_interval override (seconds)
#   stop_s    = requested sim duration (seconds)
#   sim_s     = sim seconds Shadow actually reached
#   wall_s    = wall-clock seconds the run took
#   ratio     = sim_s / wall_s (higher = Shadow kept up, <1 = stalling)
#   ok        = 1 if Shadow completed 100%, 0 if killed / incomplete

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

# shellcheck disable=SC1091
[[ -f venv/bin/activate ]] && source venv/bin/activate

# ---------- config ----------
: "${CSV:=$REPO_DIR/scaling_sweep_results.csv}"
# Sim timings: clean and simple.
#   t=0      sim starts, miners begin mining
#   t=2h     bootstrap_end, miner-distributor starts funding (coinbase
#            unlock = 60 blocks × 120s = 2h)
#   t=3h     activity_start (users wake up; distributor's funding txs
#            had 1h to be mined and mature in user wallets)
#   t=6h     sim ends → 3h of real user-tx activity
: "${STOP_S:=21600}"         # 6h sim per run
: "${BOOTSTRAP_S:=7200}"     # 2h
: "${ACTIVITY_S:=10800}"     # 3h
: "${TIMEOUT_S:=21600}"      # 6h wall (= sim time at ratio 1; slower machines may time out)
: "${SIMULATION_SEED:=12345}"

# ---------- scenario template ----------
render_scenario() {
    local N="$1" interval="$2"
    local num_miners=3

    cat <<EOF
# AUTO-GENERATED by scaling_sweep.sh
# N=$N users, total nodes = N + $num_miners miners, interval=${interval}s

general:
  stop_time: ${STOP_S}s
  simulation_seed: $SIMULATION_SEED
  bootstrap_end_time: ${BOOTSTRAP_S}s
  enable_dns_server: true
  shadow_log_level: warning
  progress: true
  runahead: 100ms
  process_threads: 2
  native_preemption: true
  daemon_defaults:
    log-level: 1
    max-log-file-size: 0
    db-sync-mode: fastest
    no-zmq: true
    non-interactive: true
    disable-rpc-ban: true
    allow-local-ip: true
  wallet_defaults:
    log-level: 1

network:
  path: gml_processing/1200_nodes_caida_with_loops.gml
  peer_mode: Dynamic

agents:
  miner-{001..003}:
    daemon: monerod
    wallet: monero-wallet-rpc
    script: agents.autonomous_miner
    start_time: 0s
    start_time_stagger: 1s
    hashrate: [34, 33, 33]
    can_receive_distributions: true

EOF

    if (( N > 0 )); then
        printf '  user-{001..%03d}:\n' "$N"
        cat <<EOF
    daemon: monerod
    wallet: monero-wallet-rpc
    script: agents.regular_user
    start_time: 600s
    start_time_stagger: 1s
    # explicit values -> bypass calibrator auto-bump for this experiment
    transaction_interval: $interval
    activity_start_time: $ACTIVITY_S
    activity_start_time_stagger: 1s
    can_receive_distributions: true

EOF
    fi

    cat <<EOF
  miner-distributor:
    script: agents.miner_distributor
    wait_time: ${BOOTSTRAP_S}s
    transaction_frequency: 30

  simulation-monitor:
    script: agents.simulation_monitor
    poll_interval: auto   # calibrated for M nodes (see calibrate.py)
EOF
}

# ---------- per-run logic ----------
ensure_header() {
    [[ -f "$CSV" ]] && return
    echo "N,M,interval,stop_s,sim_s,wall_s,ratio,ok,archive_dir" > "$CSV"
}

sweep_one() {
    local N="$1" interval="$2"
    local M=$(( N + 3 ))   # total nodes = users + 3 miners (no relays)
    local tag="N${N}_i${interval}"
    local scenario="/tmp/sweep_${tag}.scenario.yaml"
    local config="/tmp/sweep_${tag}.yaml"

    printf '\n==== sweep %s (M=%d) ====\n' "$tag" "$M"
    render_scenario "$N" "$interval" > "$scenario"

    if ! python -m scripts.scenario_parser --no-calibrate "$scenario" -o "$config" >/dev/null 2>&1; then
        echo "  expansion failed — skipping"
        echo "$N,$M,$interval,$STOP_S,0,0,0,0,FAILED_EXPAND" >> "$CSV"
        return
    fi

    # Clean state between runs
    rm -rf /tmp/monero-* /tmp/monerosim_shared 2>/dev/null || true

    local start=$SECONDS
    local ok=0
    local archive=""
    if timeout "$TIMEOUT_S" ./run_sim.sh --config "$config" --name "sweep_${tag}" >/dev/null 2>&1; then
        ok=1
    fi
    local wall=$(( SECONDS - start ))

    # CRITICAL: run_sim.sh launches `shadow` via `setsid`, so when timeout
    # SIGTERMs run_sim.sh the shadow child survives in its own session. Left
    # alone, the orphan keeps running, contaminates the next iteration's
    # /tmp + shadow.data, and consumes cores. Kill any leftover shadow and
    # monero processes before the next iteration starts.
    pkill -KILL -f "/home/lever65/.monerosim/bin/shadow .*shadow_agents\.yaml" 2>/dev/null || true
    pkill -KILL -f "/home/lever65/.monerosim/bin/monerod" 2>/dev/null || true
    pkill -KILL -f "/home/lever65/.monerosim/bin/monero-wallet-rpc" 2>/dev/null || true
    sleep 2

    # Find the archive dir we just produced
    archive=$(ls -dt archived_runs/*sweep_${tag}* 2>/dev/null | head -1 || true)

    # Parse the last Progress: line from shadow_run.log to get sim_s reached
    local sim_s=0
    if [[ -n "$archive" ]] && [[ -f "$archive/shadow_run.log" ]]; then
        # "Progress: 100% — simulated: 01:30:00.000/01:30:00, realtime: 00:03:21"
        local last
        last=$(grep '^Progress:' "$archive/shadow_run.log" | tail -1 || true)
        if [[ -n "$last" ]]; then
            local hms
            hms=$(echo "$last" | grep -oE 'simulated: [0-9:]+' | awk '{print $2}')
            # HH:MM:SS -> seconds
            if [[ "$hms" =~ ^([0-9]+):([0-9]+):([0-9]+) ]]; then
                sim_s=$(( 10#${BASH_REMATCH[1]} * 3600 + 10#${BASH_REMATCH[2]} * 60 + 10#${BASH_REMATCH[3]} ))
            fi
        fi
    fi

    local ratio=0
    if (( wall > 0 )); then
        ratio=$(awk -v s="$sim_s" -v w="$wall" 'BEGIN{printf "%.3f", s/w}')
    fi
    echo "$N,$M,$interval,$STOP_S,$sim_s,$wall,$ratio,$ok,$archive" >> "$CSV"
    printf '  sim_s=%d wall_s=%d ratio=%s ok=%d\n' "$sim_s" "$wall" "$ratio" "$ok"
}

# ---------- grid ----------
run_default_grid() {
    # No relay nodes: every non-miner is a regular_user. Total nodes M = N + 3.
    # Formula predicts safe_interval = N * M * K / C with K~3.
    # For C=256 cores:
    #   N=10  M=13  -> 1.5s  (any interval safe)
    #   N=30  M=33  -> 12s
    #   N=100 M=103 -> 121s  (interval=60 should storm)
    #   N=300 M=303 -> 1065s (interval=600 should storm)
    #   N=1000 M=1003 -> 11761s (needs huge interval)
    # For C=24 cores, multiply the above by 256/24 ~= 10.7.
    local grid=(
        # N   interval
          10  60       # safe everywhere
          30  60       # safe on C=256; maybe borderline on C=24
         100  60       # storm at any C
         100 300       # borderline C=24, safe C=256
         100 600       # safe
         300 300       # storm at any C
         300 1200      # borderline C=256, storm C=24
         300 3600      # safe at C=256
        1000 3600      # storm at C=24, borderline at C=256
        1000 12000     # safe at C=256
    )

    # Scale the grid to this machine's RAM. Empirically, Shadow + the
    # monerod+wallet-rpc processes per node consume roughly:
    #   small overhead + ~50 MB per user host
    # The limit is usually total RAM, since Shadow holds event queues for
    # every host concurrently. Be conservative — OOM kills are expensive.
    local ram_gb
    ram_gb=$(free -g 2>/dev/null | awk '/^Mem:/{print $2}')
    [[ -z "$ram_gb" ]] && ram_gb=8   # fallback
    local max_n
    if   (( ram_gb >= 256 )); then max_n=1500
    elif (( ram_gb >=  96 )); then max_n=750
    elif (( ram_gb >=  48 )); then max_n=350
    elif (( ram_gb >=  24 )); then max_n=150
    elif (( ram_gb >=  12 )); then max_n=75
    else                           max_n=30
    fi
    echo "Machine: $(nproc) cores, ${ram_gb} GB RAM → capping grid at N<=${max_n}"

    # Filter grid by max_n
    local filtered=()
    local i=0
    while (( i < ${#grid[@]} )); do
        local n="${grid[$i]}"
        if (( n <= max_n )); then
            filtered+=( "${grid[$i]}" "${grid[$((i+1))]}" )
        fi
        i=$(( i + 2 ))
    done
    local count=$(( ${#filtered[@]} / 2 ))
    echo "Running $count configurations (of ${#grid[@]} total), writing to $CSV"

    i=0
    while (( i < ${#filtered[@]} )); do
        sweep_one "${filtered[$i]}" "${filtered[$((i+1))]}"
        i=$(( i + 2 ))
    done
    echo ""
    echo "=== Results ==="
    column -t -s, "$CSV"
}

# ---------- main ----------
ensure_header

case "${1:-}" in
    --grid)
        run_default_grid
        ;;
    --help|-h|"")
        grep '^# ' "$0" | sed 's/^# \?//'
        exit 0
        ;;
    *)
        if (( $# < 2 )); then
            echo "Usage: $0 [--grid | N interval]"
            exit 1
        fi
        sweep_one "$1" "$2"
        ;;
esac
