#!/usr/bin/env bash
#
# scaling_sweep.sh — rapid-iteration tool for calibrating the Shadow
# event-storm constant (SHADOW_EVENT_COST_S) in scripts/calibrate.py.
#
# Runs a small simulation for each (N, M, interval) tuple in a grid,
# measures how fast Shadow advances simulated time relative to wall time,
# and appends results to a CSV. Each run is small (~minutes, not hours)
# so dozens of data points can be collected per day.
#
# Usage:
#   ./scripts/scaling_sweep.sh <N> <M> <interval>          # one run
#   ./scripts/scaling_sweep.sh --grid                       # run default grid
#   CSV=/tmp/results.csv ./scripts/scaling_sweep.sh --grid  # custom CSV path
#
# Fields recorded per run:
#   N         = number of user agents
#   M         = total simulated network nodes (miners + users + relays)
#   interval  = transaction_interval override (seconds)
#   stop_s    = requested sim duration (seconds)
#   sim_s     = sim seconds Shadow actually reached
#   wall_s    = wall-clock seconds the run took
#   ratio     = sim_s / wall_s (higher = Shadow kept up, <1 = stalling)
#   ok        = 1 if Shadow completed 100%, 0 if killed / incomplete

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

# shellcheck disable=SC1091
[[ -f venv/bin/activate ]] && source venv/bin/activate

# ---------- config ----------
: "${CSV:=$REPO_DIR/scaling_sweep_results.csv}"
: "${STOP_S:=7200}"          # 2h sim duration per run (~1h activity once funding matures)
: "${BOOTSTRAP_S:=2700}"     # 45m bootstrap: miners mine + coinbase matures
: "${ACTIVITY_S:=3300}"      # activity starts 10m after bootstrap, after distributor funds
: "${TIMEOUT_S:=3600}"       # kill if run takes longer than 1h wall (signals storm)
: "${SIMULATION_SEED:=12345}"

# ---------- scenario template ----------
render_scenario() {
    local N="$1" M="$2" interval="$3"
    local num_miners=3
    local num_relays=$(( M - N - num_miners ))
    if (( num_relays < 1 )); then num_relays=1; fi

    cat <<EOF
# AUTO-GENERATED by scaling_sweep.sh
# N=$N users, M=$M nodes, interval=${interval}s

general:
  stop_time: ${STOP_S}s
  simulation_seed: $SIMULATION_SEED
  bootstrap_end_time: ${BOOTSTRAP_S}s
  enable_dns_server: true
  shadow_log_level: warning
  progress: true
  runahead: 100ms
  process_threads: 2
  native_preemption: true
  daemon_defaults:
    log-level: 1
    max-log-file-size: 0
    db-sync-mode: fastest
    no-zmq: true
    non-interactive: true
    disable-rpc-ban: true
    allow-local-ip: true
  wallet_defaults:
    log-level: 1

network:
  path: gml_processing/1200_nodes_caida_with_loops.gml
  peer_mode: Dynamic

agents:
  miner-{001..003}:
    daemon: monerod
    wallet: monero-wallet-rpc
    script: agents.autonomous_miner
    start_time: 0s
    start_time_stagger: 1s
    hashrate: [34, 33, 33]
    can_receive_distributions: true

EOF

    if (( N > 0 )); then
        printf '  user-{001..%03d}:\n' "$N"
        cat <<EOF
    daemon: monerod
    wallet: monero-wallet-rpc
    script: agents.regular_user
    start_time: 600s
    start_time_stagger: 1s
    # explicit values -> bypass calibrator auto-bump for this experiment
    transaction_interval: $interval
    activity_start_time: $ACTIVITY_S
    activity_start_time_stagger: 1s
    can_receive_distributions: true

EOF
    fi

    if (( num_relays > 0 )); then
        printf '  relay-{001..%03d}:\n' "$num_relays"
        cat <<EOF
    daemon: monerod
    start_time: 60s
    start_time_stagger: 1s

EOF
    fi

    cat <<EOF
  miner-distributor:
    script: agents.miner_distributor
    wait_time: ${BOOTSTRAP_S}s
    transaction_frequency: 30

  simulation-monitor:
    script: agents.simulation_monitor
    poll_interval: 60
EOF
}

# ---------- per-run logic ----------
ensure_header() {
    [[ -f "$CSV" ]] && return
    echo "N,M,interval,stop_s,sim_s,wall_s,ratio,ok,archive_dir" > "$CSV"
}

sweep_one() {
    local N="$1" M="$2" interval="$3"
    local tag="N${N}_M${M}_i${interval}"
    local scenario="/tmp/sweep_${tag}.scenario.yaml"
    local config="/tmp/sweep_${tag}.yaml"

    printf '\n==== sweep %s ====\n' "$tag"
    render_scenario "$N" "$M" "$interval" > "$scenario"

    if ! python -m scripts.scenario_parser --no-calibrate "$scenario" -o "$config" >/dev/null 2>&1; then
        echo "  expansion failed — skipping"
        echo "$N,$M,$interval,$STOP_S,0,0,0,0,FAILED_EXPAND" >> "$CSV"
        return
    fi

    # Clean state between runs
    rm -rf /tmp/monero-* /tmp/monerosim_shared 2>/dev/null || true

    local start=$SECONDS
    local ok=0
    local archive=""
    if timeout "$TIMEOUT_S" ./run_sim.sh --config "$config" --name "sweep_${tag}" >/dev/null 2>&1; then
        ok=1
    fi
    local wall=$(( SECONDS - start ))

    # Find the archive dir we just produced
    archive=$(ls -dt archived_runs/*sweep_${tag}* 2>/dev/null | head -1 || true)

    # Parse the last Progress: line from shadow_run.log to get sim_s reached
    local sim_s=0
    if [[ -n "$archive" ]] && [[ -f "$archive/shadow_run.log" ]]; then
        # "Progress: 100% — simulated: 01:30:00.000/01:30:00, realtime: 00:03:21"
        local last
        last=$(grep '^Progress:' "$archive/shadow_run.log" | tail -1 || true)
        if [[ -n "$last" ]]; then
            local hms
            hms=$(echo "$last" | grep -oE 'simulated: [0-9:]+' | awk '{print $2}')
            # HH:MM:SS -> seconds
            if [[ "$hms" =~ ^([0-9]+):([0-9]+):([0-9]+) ]]; then
                sim_s=$(( 10#${BASH_REMATCH[1]} * 3600 + 10#${BASH_REMATCH[2]} * 60 + 10#${BASH_REMATCH[3]} ))
            fi
        fi
    fi

    local ratio=0
    if (( wall > 0 )); then
        ratio=$(awk -v s="$sim_s" -v w="$wall" 'BEGIN{printf "%.3f", s/w}')
    fi
    echo "$N,$M,$interval,$STOP_S,$sim_s,$wall,$ratio,$ok,$archive" >> "$CSV"
    printf '  sim_s=%d wall_s=%d ratio=%s ok=%d\n' "$sim_s" "$wall" "$ratio" "$ok"
}

# ---------- grid ----------
run_default_grid() {
    # Picked to bracket the predicted K: for C=256 cores,
    #   safe_interval = N * M * K / C
    # With K~3, interval_safe ≈ N*M/85. Rows below span both "should
    # work" and "should stall" regimes.
    #
    # Also useful data: different N at same M (isolate the N term),
    # different M at same N (isolate the M term), and different
    # intervals at same (N,M) (find the ratio=1 threshold).
    local grid=(
        # N  M    interval  -- predicted-safe minimum (K=3, C=256) in comments
         20 100   15    # predicted 23s; 15s should just barely fail or just work
         20 100   60    # predicted 23s; 60s clearly safe
         50 200   60    # predicted 117s; 60s should storm
         50 200  120    # predicted 117s; borderline
         50 200  300    # predicted 117s; clearly safe
        100 500  300    # predicted 586s; should storm
        100 500  600    # predicted 586s; borderline
        100 500 1200    # predicted 586s; clearly safe
        100 1000 600    # predicted 1172s; should storm (matches known-failing config)
    )
    local n=$(( ${#grid[@]} / 3 ))
    echo "Running $n configurations, writing to $CSV"
    local i=0
    while (( i < ${#grid[@]} )); do
        sweep_one "${grid[$i]}" "${grid[$((i+1))]}" "${grid[$((i+2))]}"
        i=$(( i + 3 ))
    done
    echo ""
    echo "=== Results ==="
    column -t -s, "$CSV"
}

# ---------- main ----------
ensure_header

case "${1:-}" in
    --grid)
        run_default_grid
        ;;
    --help|-h|"")
        grep '^# ' "$0" | sed 's/^# \?//'
        exit 0
        ;;
    *)
        if (( $# < 3 )); then
            echo "Usage: $0 [--grid | N M interval]"
            exit 1
        fi
        sweep_one "$1" "$2" "$3"
        ;;
esac
