general:
  stop_time: 5 min
  seed: 1
  parallelism: 0
  bootstrap_end_time: 0 sec
  log_level: info
  heartbeat_interval: 1 sec
  data_directory: shadow.data
  template_directory: null
  progress: false
  model_unblocked_syscall_latency: true
network:
  graph:
    type: 1_gbit_switch
  use_shortest_path: true
experimental:
  use_sched_fifo: false
  use_syscall_counters: true
  use_object_counters: true
  use_preload_libc: true
  use_preload_openssl_rng: true
  use_preload_openssl_crypto: false
  use_memory_manager: false
  use_cpu_pinning: true
  use_worker_spinning: true
  runahead: 1 ms
  use_dynamic_runahead: false
  socket_send_buffer: 131072 B
  socket_send_autotune: true
  socket_recv_buffer: 174760 B
  socket_recv_autotune: true
  interface_qdisc: fifo
  strace_logging_mode: off
  max_unapplied_cpu_latency: 1 μs
  unblocked_syscall_latency: 1 μs
  unblocked_vdso_latency: 10 ns
  scheduler: thread-per-core
  report_errors_to_stderr: true
  use_new_tcp: false
  native_preemption_enabled: false
  native_preemption_native_interval: 100 ms
  native_preemption_sim_interval: 10 ms
hosts:
  a0:
    network_node_id: 0
    processes:
    - path: /usr/local/bin/monerod-v0.18.4.0
      args: --testnet --log-level=1 --log-file=/dev/stdout --data-dir=/tmp/monero-a0 --non-interactive --no-sync --disable-dns-checkpoints --disable-rpc-ban --max-concurrency=1 --p2p-bind-ip=11.0.0.1 --p2p-bind-port=28080 --rpc-bind-port=0 --no-igd --no-zmq --add-exclusive-node=11.0.0.2:28081 --out-peers=1 --in-peers=1 --max-connections-per-ip=1 --limit-rate-up=1024 --limit-rate-down=1024
      environment: {}
      start_time: 5 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state: running
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  a1:
    network_node_id: 0
    processes:
    - path: /usr/local/bin/monerod-v0.18.4.0
      args: --testnet --log-level=1 --log-file=/dev/stdout --data-dir=/tmp/monero-a1 --non-interactive --no-sync --disable-dns-checkpoints --disable-rpc-ban --max-concurrency=1 --p2p-bind-ip=11.0.0.2 --p2p-bind-port=28081 --rpc-bind-port=0 --no-igd --no-zmq --add-exclusive-node=11.0.0.1:28080 --out-peers=1 --in-peers=1 --max-connections-per-ip=1 --limit-rate-up=1024 --limit-rate-down=1024
      environment: {}
      start_time: 5 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state: running
    ip_addr: null
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
